<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-GameNewsHub.Sync-54ad5b94-abf3-4013-a311-6caab1bbd0cb</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GameNewsHub.Data\GameNewsHub.Data.csproj" />
    </ItemGroup>
</Project>
